create table if not exists episode_transfer( id bigserial not null, episode_id bigint, hierarchy_mapping_from bigint, hierarchy_mapping_to bigint, new_address varchar(2000), alternate_mobile_no varchar(15), reason varchar(250), final_status varchar(50), remarks varchar(255), updated_by bigint, updated_on timestamp, added_by bigint, created_at timestamp, deleted boolean, transfer_type varchar(1), action_status varchar(50), action_taken_date timestamp, nature_of_transfer varchar(10), primary key (id));
alter table if exists episode_transfer add column relation_type varchar(255)

CREATE TABLE IF NOT EXISTS episode_transfer_aud( id bigint NOT NULL, REV integer NOT NULL, REVTYPE smallint, episode_id bigint, relation_type text, hierarchy_from bigint, hierarchy_to bigint, new_address text, alternate_mobile_no text, reason text, final_status text, remarks text, created_at timestamp, updated_on timestamp, added_by bigint, updated_by bigint, deleted boolean, transfer_type char(1), action_status text, action_taken_date timestamp, nature_of_transfer text, PRIMARY KEY (id, REV));
alter table if exists episode_transfer_aud add column hierarchy_mapping_from int8
alter table if exists episode_transfer_aud add column hierarchy_mapping_to int8
CREATE SEQUENCE if not exists public.hibernate_sequence START 1;

create table if not exists REVINFO( REV integer generated by default as identity, REVTSTMP bigint, primary key (REV));

alter table if exists episode_transfer_aud add constraint FKtg0ahm4jhhc1lq10ndxg35qni foreign key (rev) references revinfo
